region       = "ap-south-1"
project_name = "demo"
vpc_cidr     = "10.0.0.0/16"
subnet_cidr  = "10.0.1.0/24"
az           = "ap-south-1a"
my_ip        = "YOUR_PUBLIC_IP/32"
key_name     = "your-keypair-name"
aws_region = "ap-south-1"